### ISSUE TITLE
Neo4jError: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by KrishnaPravin** [neo4j-examples/neo4j-movies-template#47]
Steps to reproduce:
1. load all csv files
2. `npm install` in /api
3. `node api.js`

```sh
Neo4jError: Client network socket disconnected before secure TLS connection was established

    at captureStacktrace (/Users/krs/Documents/Krishna/TryCode/neo4j-movies-template/api/node_modules/neo4j-driver/lib/v1/result.js:199:15)
    at new Result (/Users/krs/Documents/Krishna/TryCode/neo4j-movies-template/api/node_modules/neo4j-driver/lib/v1/result.js:65:19)
    at Session._run (/Users/krs/Documents/Krishna/TryCode/neo4j-movies-template/api/node_modules/neo4j-driver/lib/v1/session.js:152:14)
    at Session.run (/Users/krs/Documents/Krishna/TryCode/neo4j-movies-template/api/node_modules/neo4j-driver/lib/v1/session.js:130:19)
    at Object.getAll (/Users/krs/Documents/Krishna/TryCode/neo4j-movies-template/api/models/genres.js:5:18)
    at exports.list (/Users/krs/Documents/Krishna/TryCode/neo4j-movies-template/api/routes/genres.js:36:10)
    at Layer.handle [as handle_request] (/Users/krs/Documents/Krishna/TryCode/neo4j-movies-template/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/krs/Documents/Krishna/TryCode/neo4j-movies-template/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/krs/Documents/Krishna/TryCode/neo4j-movies-template/api/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/krs/Documents/Krishna/TryCode/neo4j-movies-template/api/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by xv-jasper-b** [comment]
One reason for this is using an old Neo4j driver on a new Neo4j database, and can be fixed by updating the driver dependency. 

_(Btw, please check out drivine.org - it is a great way to work with Neo4j on Node.js)_

**Comment by jasperblues** [comment]
One reason for this is using an old Neo4j driver on a new Neo4j database, and can be fixed by updating the driver dependency.

_(Btw, please check out drivine.org - it is a great way to work with Neo4j on Node.js)._

**Comment by KrishnaPravin** [comment]
@jasperblues I've updated the driver and now it's working. Thank You.
```
"neo4j-driver": "^4.0.2"
```
